@startuml

component AppComponent
component HeaderComponent #lightgreen
component EmpireFormComponent #lightgreen
component FileInputComponent #lightgreen

AppComponent -- HeaderComponent
AppComponent -- EmpireFormComponent
EmpireFormComponent -- FileInputComponent

@enduml
