INSERT INTO "ROUTES"(ORIGIN, DESTINATION, TRAVEL_TIME) VALUES('Tatooine', 'Dagobah', 6);
INSERT INTO "ROUTES"(ORIGIN, DESTINATION, TRAVEL_TIME) VALUES('Dagobah', 'Endor', 4);
INSERT INTO "ROUTES"(ORIGIN, DESTINATION, TRAVEL_TIME) VALUES('Dagobah', 'Hoth', 1);
INSERT INTO "ROUTES"(ORIGIN, DESTINATION, TRAVEL_TIME) VALUES('Hoth', 'Endor', 1);
INSERT INTO "ROUTES"(ORIGIN, DESTINATION, TRAVEL_TIME) VALUES('Tatooine', 'Hoth', 6);
